### ISSUE TITLE
Readme changes

### ISSUE THREAD

**Issue by anath93** [onlogic/Updating-to-Jetpack-6-for-Aetina-Jetson#1]
please correct the typo,

Current:
Step 1: Unzip the downloaded files in the /home/nvidia/nvidia_sdk directory
For the Patch Sudo tar zxvf PATCH_[Your File Version].tar.gz

change to:
For the Patch sudo tar -zxvf PATCH_[Your File Version].tar.gz

current:
Step 5: Jetson Image Installation
sudo ./tools/kernel_flash/l4t_initrd_flash.sh --external-device nvme0n1p1 -p "-c ./bootloader/generic/cfg/flash_t234_qspi.xml" -c ./tools/kernel_flash/flash_l4t_t234_nvme.xml --showlogs --network usb0 jetson-orin-nanodevkit nvme0n1p1

change:
sudo ./tools/kernel_flash/l4t_initrd_flash.sh --external-device nvme0n1p1 -p "-c ./bootloader/generic/cfg/flash_t234_qspi.xml" -c ./tools/kernel_flash/flash_l4t_t234_nvme.xml --showlogs --network usb0 jetson-orin-nano-devkit nvme0n1p1

**Comment by colewangsness** [comment]
Thank you for your submission. Change 1 accepted, Change 2 accepted, previous samples show missing "-"
